server.port=8080
app.message=Welcome from DEV profile — Odyssey RPG

spring.datasource.url=jdbc:sqlite:odyssey-dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=true
